local VehicleList = {
    {
        acePerm = "vehicles.blacklisted",
        vehicles = {
            "deathbike",
            "deathbike2",
            "deathbike3",
            "oppressor",
            "oppressor2",
            "menacer",
            "vigilante",
            "phantom2",
            "deluxo",
            "toreador",
            "trophytruck",
            "trophytruck2",
            "wastelander",
            "cerberus",
            "cerberus2",
            "cerberus3",
            "policeold1",
            "policeold2",
            "minitank",
            "blazer5",
            "bruiser",
            "bruiser2",
            "bruiser3",
            "zhaba",
            "scarab",
            "scarab2",
            "scarab3",
            "voltic2"
        },
        deleteVeh = true
    },
    {
        acePerm = "vehicles.coOwner",
        vehicles = {
            "ed209v3",
            "1989",
            "asylum",
            "batpod",
            "batwing",
            "bm66",
            "mk2",
            "proto",
            "snyder",
            "tumbler",
            "khanjali",
            "thruster",
            "kosatka"
        },
        deleteVeh = true
    },
    {
        acePerm = "vehicles.fib",
        vehicles = {

        }
    },
    -- {
    --     acePerm = "vehicles.leo",
    --     vehicles = {
    --         "trualamo",
    --         "trualamo2",
    --         "trualamo3",
    --         "trualamo4",
    --         "umkalamo",
    --         "trubuffalo",
    --         "trubuffalo2",
    --         "umkbuffalo",
    --         "polcaracara",
    --         "polumkcara",
    --         "policefug",
    --         "policefug2",
    --         "policefug3",
    --         "nkgauntlet4",
    --         "polgresley",
    --         "polumkgresley",
    --         "umkscout",
    --         "pwcart",
    --         "bcsostanierumk"
    --     },
    --     deleteVeh = false
    -- },
    -- {
    --     acePerm = "vehicles.noose",
    --     vehicles = {
    --         "centurion",
    --         "centurionfib",
    --         "centurionlssd",
    --         "centurionlspd",
    --         "riot3",
    --         "nooseair",
    --         "nooseair2",
    --         "nooseair3",
    --         "noosesep",
    --         "noosesep2",
    --         "noosesep3",
    --         "noosesep4",
    --         "noosesep5",
    --         "noosetru",
    --         "noosetru2",
    --         "noosetru3",
    --         "riotpickupb",
    --         "riotpickupb2",
    --         "riotpickupc",
    --         "riotpickupc2",
    --         "riotpickupy",
    --         "riotpickupy2",
    --         "riotsuve",
    --         "riotsuve2",
    --         "riotsuvg",
    --         "riotsuvg2",
    --         "riotsuvg3",
    --         "riotsuvg4",
    --         "riotvanr",
    --         "riotvanr2",
    --         "riotvans",
    --         "riotvans2",
    --         "riotvans3",
    --         "riotvans4",
    --         "bcat",
    --         "bcat1",
    --         "riot",
    --         "riot2",
    --         "annhilator"
    --     },
    --     deleteVeh = false
    -- },
    -- {
    --     acePerm = "vehicles.pia",
    --     vehicles = {
    --         "noosecruiser",
    --         "noosepatriot",
    --         "noosebp",
    --         "noosebp2",
    --         "noosebp3",
    --         "noosebp4",
    --         "noosebp5",
    --         "noosebp6",
    --         "noosepia",
    --         "noosepia2",
    --         "noosepia3",
    --         "noosepia4",
    --         "noosepia5",
    --         "noosesea",
    --         "noosesea2"
    --     },
    --     deleteVeh = false
    -- },
    -- {
    --     acePerm = "vehicles.sahp",
    --     vehicles = {
    --         "sahp",
    --         "sahp1a",
    --         "sahp1b",
    --         "sahp1c",
    --         "sahp1d",
    --         "sahp2",
    --         "sahp2a",
    --         "sahp3",
    --         "sahp4",
    --         "sahp4a",
    --         "sahp5",
    --         "sahp5a",
    --         "sahp6",
    --         "sahp6a",
    --         "sahp22",
    --         "sahp22a",
    --         "sahpair",
    --         "sahpb",
    --         "sahpb2",
    --         "policeb",
    --         "polmav2"
    --     },
    --     deleteVeh = false
    -- },
    -- {
    --     acePerm = "vehicles.bcso",
    --     vehicles = {
    --         "bcsofug",
    --         "bcsoscoutII",
    --         "bcsosecspeedo",
    --         "bcsosectorrence",
    --         "bcsostanier",
    --         "bcsostanierk9",
    --         "bcsoalamo"
    --     },
    --     deleteVeh = false
    -- },
    -- {
    --     acePerm = "vehicles.lspd",
    --     vehicles = {
    --         "sbearcat",
    --         "pcaddyRB",
    --         "lspdb",
    --         "poleveron",
    --         "police",
    --         "police2",
    --         "police3",
    --         "police4",
    --         "police42old",
    --         "policeslick",
    --         "polriot",
    --         "polsadlerk9",
    --         "polspeedo",
    --         "pscout",
    --         "pscoutnew",
    --         "swatstalker"
    --     },
    --     deleteVeh = false
    -- },
    {
        acePerm = "vehicles.nationalguard",
        vehicles = {
            "patrolboat",
            "dinghy5",
            "buzzard",
            "cargobob",
            "cargobob3",
            "cargobob4",
            "hunter",
            "savage",
            "valkyrie",
            "valkyrie2",
            "annihilator2",
            "apc",
            "barracks",
            "barracks2",
            "barracks3",
            "crusader",
            "halftrack",
            "rhino",
            "trailersmall2",
            "avenger",
            "avenger2",
            "hydra",
            "lazer",
            "squaddie",
            "amtrak",
            "cougar4",
            "hh60",
            "jltv",
            "matv",
            "msquaddie",
            "msquaddie2",
            "squaddie2",
            "squaddie3"
        },
        deleteVeh = true
    },
    {
        acePerm = "vehicles.planes",
        vehicles = {
            "alphaz1",
            "besra",
            "blimp",
            "blimp2",
            "blimp3",
            "cargoplane",
            "cargoplane2",
            "cuban800",
            "dodo",
            "duster",
            "howard",
            "jet",
            "luxor",
            "luxor2",
            "mammatus",
            "microlight",
            "miljet",
            "mogul",
            "molotok",
            "nimbus",
            "nokota",
            "pyro",
            "rogue",
            "seabreeze",
            "shamal",
            "starling",
            "sting",
            "tula",
            "velum",
            "velum2",
            "vestra",
            "volatol"
        },
        deleteVeh = true
    },
    {
        acePerm = "vehicles.helicopters",
        vehicles = {
            "buzzard2",
            "frogger",
            "frogger2",
            "havok",
            "mverick",
            "seasparrow",
            "skylift",
            "supervolito",
            "supervolito2",
            "swift",
            "swift2",
            "volatus",
            "seasparrow2",
            "seasparrow3"
        },
        deleteVeh = true
    },
    {
        acePerm = "vehicles.boats",
        vehicles = {
            "dinghy",
            "dinghy2",
            "dinghy3",
            "dinghy4",
            "jetmax",
            "marquis",
            "seashark",
            "seashark2",
            "seashark3",
            "speeder",
            "speeder2",
            "squalo",
            "submersible",
            "submersible2",
            "suntrap",
            "toro",
            "toro2",
            "tropic",
            "tropic2",
            "tug",
            "avisa",
            "longfin"
        },
        deleteVeh = true
    }
}

RegisterNetEvent("fn_whitelist:checkVehicle")
AddEventHandler("fn_whitelist:checkVehicle", function (currentlyInVehicle, playerId)
    for i = 1, #VehicleList do
        for x = 1, #VehicleList[i].vehicles do
            local hasAccessToCategory = IsPlayerAceAllowed(playerId, VehicleList[i].acePerm)
            if currentlyInVehicle == GetHashKey(VehicleList[i].vehicles[x]) and hasAccessToCategory == false then
                TriggerClientEvent("fn_whitelist:vehicleBlacklisted", playerId, VehicleList[i].deleteVeh)
            end
        end
    end
end)